### ISSUE TITLE
bs.js 제거

### ISSUE THREAD

**Issue by sairion** [green-labs/rescript-bindings#20]
사실상 비 rescript 프로젝트에서 이 바인딩 패키지들을 사용할 일은 없으므로, bs.js를 포함시킬 필요가 없습니다.
npm 패키지에서도 npmignore 등의 방법으로 exclude되어야 합니다.

**Comment by namenu** [comment]
.bs.js 때문에 컴파일러가 clean 을 시도하는 것인가 싶어서... 겸사겸사 지워봅니다.
