### ISSUE TITLE
Wrong package name on `rescript-date-fns`

### ISSUE THREAD

**Issue by vmarcosp** [green-labs/rescript-bindings#40]
Hey 👋
First off, thanks for this package! I have been using these bindings in production projects.
I'm trying to use the package `@greenlabs/rescript-date-fns`, but I got this error:
![Captura de Tela 2022-12-06 às 10 01 42](https://user-images.githubusercontent.com/20327229/205919712-578bc3b0-6928-4d2e-b903-c641475e42b8.png)

I've checked the package's bsconfig.json file and the package name is `rescript-date-fns`. AFAIK the`package.json` and the `bsconfig.json` should use the same package name, right? In this case, the name should be `@greenlabs/rescript-date-fns` instead of `rescript-date-fns`.

**Comment by minuukang** [comment]
Thank you for the issue!

https://github.com/green-labs/rescript-bindings/pull/41

**Comment by minuukang** [comment]
You can using the correct package `@greenlabs/rescript-date-fns@1.0.0` ! Thank you so much for find that issue ❤️

**Comment by vmarcosp** [comment]
Thank YOU @minuukang and @green-labs for this amazing project ❤️
