### ISSUE TITLE
rescript-react-hook-form validation not working ?

### ISSUE THREAD

**Issue by DCKT** [green-labs/rescript-bindings#51]
Hello, 

I just found your bindings for `react-hook-form` that looks pretty dope and tried it but I can't make the validation working using the example in the README. 

I don't know if it's a bug with the bindings or my implementation, here is the [repo](https://github.com/DCKT/rescript-react-hook-form) with the repro & the deployed form.

Thanks :)

**Comment by namenu** [comment]
@DCKT Thanks for the issue.

The bindings for react-hook-form have not been managed for long time.
Have you checked https://github.com/green-labs/ppx_react_hook_form ?

**Comment by DCKT** [comment]
How that's maybe the reason, I've found the bindings with the ppx but didn't tried it. 
I would have prefered to not using a ppx, coming from reform & lenses which seemes to not be maintained anymore, without OCaml and some specifics knownledges it's pretty hard to update it by itself. 

I will take a look anyway :) thanks for your answer !
